import type { ManagedSource } from '@qiushuiai-airadar/runtime'

const legacy: Array<Omit<ManagedSource, 'sortOrder' | 'status' | 'language'>> =
  [
    {
      id: 'x_openai',
      slug: 'x_openai',
      name: 'X / OpenAI',
      type: 'x',
      externalIdentity: 'OpenAI',
    },
    {
      id: 'x_anthropic',
      slug: 'x_anthropic',
      name: 'X / Anthropic',
      type: 'x',
      externalIdentity: 'AnthropicAI',
    },
    {
      id: 'x_karpathy',
      slug: 'x_karpathy',
      name: 'X / Andrej Karpathy',
      type: 'x',
      externalIdentity: 'karpathy',
    },
    {
      id: 'x_ilyasut',
      slug: 'x_ilyasut',
      name: 'X / Ilya Sutskever',
      type: 'x',
      externalIdentity: 'ilyasut',
    },
    {
      id: 'x_akshay_pachaar',
      slug: 'x_akshay_pachaar',
      name: 'X / Akshay Pachaar',
      type: 'x',
      externalIdentity: 'akshay_pachaar',
    },
    {
      id: 'x_saboo_shubham',
      slug: 'x_saboo_shubham',
      name: 'X / Shubham Saboo',
      type: 'x',
      externalIdentity: 'Saboo_Shubham_',
    },
    {
      id: 'x_langchain',
      slug: 'x_langchain',
      name: 'X / LangChain',
      type: 'x',
      externalIdentity: 'LangChain',
    },
    {
      id: 'x_llama_index',
      slug: 'x_llama_index',
      name: 'X / LlamaIndex',
      type: 'x',
      externalIdentity: 'llama_index',
    },
    {
      id: 'x_ycombinator',
      slug: 'x_ycombinator',
      name: 'X / Y Combinator',
      type: 'x',
      externalIdentity: 'ycombinator',
    },
    {
      id: 'x_garrytan',
      slug: 'x_garrytan',
      name: 'X / Garry Tan',
      type: 'x',
      externalIdentity: 'garrytan',
    },
    {
      id: 'x_levie',
      slug: 'x_levie',
      name: 'X / Aaron Levie',
      type: 'x',
      externalIdentity: 'levie',
    },
    {
      id: 'x_amanda_askell',
      slug: 'x_amanda_askell',
      name: 'X / Amanda Askell',
      type: 'x',
      externalIdentity: 'AmandaAskell',
    },
    {
      id: 'x_petergyang',
      slug: 'x_petergyang',
      name: 'X / Peter G. Yang',
      type: 'x',
      externalIdentity: 'petergyang',
    },
    {
      id: 'x_bcherny',
      slug: 'x_bcherny',
      name: 'X / Brian Cherny',
      type: 'x',
      externalIdentity: 'bcherny',
    },
    {
      id: 'x_catwu',
      slug: 'x_catwu',
      name: 'X / Cat Wu',
      type: 'x',
      externalIdentity: '_catwu',
    },
    {
      id: 'x_gregisenberg',
      slug: 'x_gregisenberg',
      name: 'X / Greg Isenberg',
      type: 'x',
      externalIdentity: 'gregisenberg',
    },
    {
      id: 'yt_anthropic',
      slug: 'yt_anthropic',
      name: 'YouTube / Anthropic',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@anthropic-ai',
    },
    {
      id: 'yt_claude',
      slug: 'yt_claude',
      name: 'YouTube / Claude',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@claude/videos',
    },
    {
      id: 'yt_openai',
      slug: 'yt_openai',
      name: 'YouTube / OpenAI',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@OpenAI',
    },
    {
      id: 'yt_ibm_tech',
      slug: 'yt_ibm_tech',
      name: 'YouTube / IBM Technology',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@IBMTechnology',
    },
    {
      id: 'yt_ycombinator',
      slug: 'yt_ycombinator',
      name: 'YouTube / Y Combinator',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@ycombinator',
    },
    {
      id: 'yt_lennys_podcast',
      slug: 'yt_lennys_podcast',
      name: "YouTube / Lenny's Podcast",
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@LennysPodcast',
    },
    {
      id: 'yt_sequoia',
      slug: 'yt_sequoia',
      name: 'YouTube / Sequoia Capital',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@sequoiacapital',
    },
    {
      id: 'yt_ai_advantage',
      slug: 'yt_ai_advantage',
      name: 'YouTube / AI Advantage',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@aiadvantage',
    },
    {
      id: 'yt_tiago_forte',
      slug: 'yt_tiago_forte',
      name: 'YouTube / Tiago Forte',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@TiagoForte',
    },
    {
      id: 'yt_nate_herk',
      slug: 'yt_nate_herk',
      name: 'YouTube / Nate Herk',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@nateherk',
    },
    {
      id: 'yt_cole_medin',
      slug: 'yt_cole_medin',
      name: 'YouTube / Cole Medin',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@ColeMedin',
    },
    {
      id: 'yt_jeff_su',
      slug: 'yt_jeff_su',
      name: 'YouTube / Jeff Su',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@JeffSu',
    },
    {
      id: 'yt_ali_abdaal',
      slug: 'yt_ali_abdaal',
      name: 'YouTube / Ali Abdaal',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@aliabdaal',
    },
    {
      id: 'yt_dan_koe',
      slug: 'yt_dan_koe',
      name: 'YouTube / Dan Koe',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@DanKoeTalks',
    },
    {
      id: 'yt_greg_isenberg',
      slug: 'yt_greg_isenberg',
      name: 'YouTube / Greg Isenberg',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@GregIsenberg',
    },
    {
      id: 'yt_ishan_sharma',
      slug: 'yt_ishan_sharma',
      name: 'YouTube / Ishan Sharma',
      type: 'youtube',
      externalIdentity: 'https://www.youtube.com/@IshanSharma7390',
    },
    {
      id: 'openai_news',
      slug: 'openai_news',
      name: 'OpenAI News',
      type: 'rss',
      externalIdentity: 'https://openai.com/news/rss.xml',
    },
  ]

export const retiredSourceIds = [
  'douyin_qinghua_jiang',
  'wechat_zhangzhang_ai',
  'xhs_itechtokai',
] as const

const initiallyEnabled = new Set(['x_openai', 'yt_openai', 'openai_news'])

export const initialSources: ManagedSource[] = legacy.map(
  (source, sortOrder) => ({
    ...source,
    language: 'en',
    status: initiallyEnabled.has(source.id) ? 'enabled' : 'disabled',
    sortOrder,
  })
)

export const legacySourceCount = legacy.length
